### ISSUE TITLE
Checkmate not found error

### ISSUE THREAD

**Issue by raj-mehra** [tcosolutions/betterscan#184]
Hello @marcinguy I tried to run the command sh <(curl https://raw.githubusercontent.com/tcosolutions/betterscan/main/cli.sh)
after the initial docker setup i get the following error 

```
sh <(curl https://raw.githubusercontent.com/tcosolutions/betterscan-ce/main/cli-html.sh)


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   699  100   699    0     0   7724      0 --:--:-- --:--:-- --:--:--  7766
/bin/sh: 1: checkmate: not found
/bin/sh: 1: checkmate: not found
/bin/sh: 1: checkmate: not found
/bin/sh: 1: checkmate: not found

```

Am i missing something, or my setup is wrong?? Cause this worked without doing anything the last time i tried. 

Thank you so much for your help in advance :)

**Comment by marcinguy** [comment]
@raj-mehra ok cool. Thanks. Did you have any success/progress with it? Having more people involved/working on the project would be great

**Comment by marcinguy** [comment]
@raj-mehra Let me know if you need anything from me, access or something

**Comment by marcinguy** [comment]
Closing for now. Please reopen when needed

**Comment by marcinguy** [comment]
FYI I guess u don’t see my gh action logs but here it errors out
```
9.583 'list' object has no attribute 'keys'
------
Dockerfile:53
--------------------
  52 |     # Clone the checkmate repository and install
  53 | >>> RUN git clone -b checkmate3-cli https://github.com/***/checkmate-ce.git /checkmate-ce && \
  54 | >>>     cd /checkmate-ce && \
  55 | >>>     pip install pip && \
  56 | >>>     pip install --upgrade pip && \
  57 | >>>     pip install poetry && \
  58 | >>>     poetry install
  59 |        
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone -b checkmate3-cli https://github.com/***/checkmate-ce.git /checkmate-ce &&     cd /checkmate-ce &&     pip install pip &&     pip install --upgrade pip &&     pip install poetry &&     poetry install" did not complete successfully: exit code: 1
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c git clone -b checkmate3-cli https://github.com/***/checkmate-ce.git /checkmate-ce &&     cd /checkmate-ce &&     pip install pip &&     pip install --upgrade pip &&     pip install poetry &&     poetry install" did not complete successfully: exit code: 1
```
🤷‍♂️

**Comment by raj-mehra** [comment]
> @raj-mehra FYI I guess u don’t see my gh action logs but here it errors out
> 
> ```
> 9.583 'list' object has no attribute 'keys'
> ------
> Dockerfile:53
> --------------------
>   52 |     # Clone the checkmate repository and install
>   53 | >>> RUN git clone -b checkmate3-cli https://github.com/***/checkmate-ce.git /checkmate-ce && \
>   54 | >>>     cd /checkmate-ce && \
>   55 | >>>     pip install pip && \
>   56 | >>>     pip install --upgrade pip && \
>   57 | >>>     pip install poetry && \
>   58 | >>>     poetry install
>   59 |        
> --------------------
> ERROR: failed to solve: process "/bin/sh -c git clone -b checkmate3-cli https://github.com/***/checkmate-ce.git /checkmate-ce &&     cd /checkmate-ce &&     pip install pip &&     pip install --upgrade pip &&     pip install poetry &&     poetry install" did not complete successfully: exit code: 1
> Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c git clone -b checkmate3-cli https://github.com/***/checkmate-ce.git /checkmate-ce &&     cd /checkmate-ce &&     pip install pip &&     pip install --upgrade pip &&     pip install poetry &&     poetry install" did not complete successfully: exit code: 1
> ```
> 
> 🤷‍♂️

Hey sorry for the late reply, thanks for the logs. I'll try to fix it today :)

**Comment by marcinguy** [comment]
Thank for you help @raj-mehra I added you as a project memeber, so you can see GH Action outputs, make PR etc.

Now the images build but somehow "checkmate" command (underlying "horse" powering the solution) is not visible/accessible in the image

Please take a look, maybe you will have an idea what could be wrong.

Thanks in advance
