### ISSUE TITLE
git not found

### ISSUE THREAD

**Issue by mattanimation** [tcosolutions/betterscan#190]
I think there may be an issue where git isn't installed on the latest container build? Every time I run the script I just get:
`/bin/sh: 1: git: not found` for each call to checkmate in the script.

I've tried:
 - both versions of the script

OS: MacOS Sonoma 14.5
Shell: bash and zsh
Docker Desktop: latest version

**Comment by marcinguy** [comment]
Have the same error :)

**Comment by marcinguy** [comment]
Actually I have an error that `checkmate` is missing, despite being build in the image.

```
Status: Downloaded newer image for sunsolution/betterscan-worker-cli:latest
/bin/sh: 1: checkmate: not found
/bin/sh: 1: checkmate: not found
/bin/sh: 1: checkmate: not found
/bin/sh: 1: checkmate: not found
```
 🤷‍♂️

**Comment by mattanimation** [comment]
can confirm that today running the script now has the same output:
```Digest: sha256:c3e717b86b2c1357068992a4f1e50f94187439b631081c3dc96a191dd879ed1c
Status: Downloaded newer image for sunsolution/betterscan-worker-cli:latest
/bin/sh: 1: checkmate: not found
/bin/sh: 1: checkmate: not found
/bin/sh: 1: checkmate: not found
/bin/sh: 1: checkmate: not found
```

**Comment by marcinguy** [comment]
I think I found the root cause of the issue. Rebuilding images now
